namespace ProConstructionsManagment.Desktop.Enums
{
    public enum ViewTypes
    {
        Main,
        MainNavigation,
        Employee,
        Employees,
        EmployeeNavigation,
        EmployeesNavigation,
        EmployeesForHire,
        HiredEmployees,
        AddEmployee,
        Project,
        ProjectCosts,
        Projects,
        ProjectNavigation,
        ProjectCostsNavigation,
        ProjectsNavigation,
        OpenedProjects,
        ProjectsToStart,
        ProjectSettlements,
        EndedProjects,
        AddProject,
        AddProjectCost,
        Client,
        Clients,
        ClientsNavigation,
        AddClient,
        ClientNavigation,
        AddProjectCostNavigation
    }
}