// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using ProConstructionsManagment.Infrastructure.Data;

namespace ProConstructionsManagment.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectContext))]
    internal class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProConstructionsManagment.Infrastructure.Data.Entities.Project", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("Agreement")
                    .HasColumnType("bit");

                b.Property<string>("ContactEmail")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ContactLastName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ContactName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ContactPhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DateOfPayment")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DateOfPaymentDelivery")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EndDate")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("NumberOfEmployees")
                    .HasColumnType("int");

                b.Property<int>("NumberOfHours")
                    .HasColumnType("int");

                b.Property<int>("NumerOfCandidates")
                    .HasColumnType("int");

                b.Property<bool>("PaymentProtocol")
                    .HasColumnType("bit");

                b.Property<int>("PaymentStatus")
                    .HasColumnType("int");

                b.Property<int>("PercentageOfImplementation")
                    .HasColumnType("int");

                b.Property<string>("PlaceOfPerformance")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("RequiredNumberOfEmployees")
                    .HasColumnType("int");

                b.Property<string>("StartDate")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Projects");
            });
#pragma warning restore 612, 618
        }
    }
}